# 项目相关配置
ruoyi:
  # 名称
  name: Token
  # 版本
  version: 0.1
  # 文件路径 示例（ Windows配置D:/token/uploadPath，Linux配置 /home/token/uploadPath）
  profile: D:/token/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

spring:
  profiles:
    active: dev,druid

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: ${token.server.port}
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.token: debug
    org.springframework: warn
